# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, base16Bytestring, binary, cryptohash, doctest, hlint, HTTP
, networkUri, parsec, QuickCheck, tasty, tastyHunit
, tastyQuickcheck, testFrameworkQuickcheck2
}:

cabal.mkDerivation (self: {
  pname = "functorrent";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    base16Bytestring binary cryptohash HTTP networkUri parsec
    QuickCheck tasty tastyHunit
  ];
  testDepends = [
    doctest hlint QuickCheck tasty tastyHunit tastyQuickcheck
    testFrameworkQuickcheck2
  ];
  meta = {
    description = "A Bit-torrent client";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
  };
})
