# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ haskellPackages ? (import <nixpkgs> {}).haskellPackages }:

with haskellPackages; cabal.mkDerivation (self: {
  pname = "functorrent";
  version = "0.1.0.0";
  src = "./.";
  isLibrary = true;
  isExecutable = true;
  buildTools = [ cabalInstall ];
  buildDepends = [
    base16Bytestring binary cryptohash HTTP networkUri parsec tasty
    tastyHunit
  ];
  testDepends = [ doctest hlint tasty tastyHunit ];
  meta = {
    description = "A Bit-torrent client";
    license = self.stdenv.lib.licenses.gpl3;
    platforms = self.ghc.meta.platforms;
  };
})
